### ISSUE TITLE
Is there any way to keep open bot even my docker is off?

### ISSUE THREAD

**Issue by Lagari-1** [muerek/discord-interval-timer-bot#1]
Hi, 
Thanks for your great work. I need some help. I want to use bot even my computer(also docker) is off. Is there any way to use all bot functionalities when docker is off? Or do I have to keep open my docker if I use bot?

**Comment by muerek** [comment]
To my knowledge, there is no option of running it all within Discord. You will have to provide the infrastructure for the bot, and the bot will only be online if that infrastructure is running. I have used a Raspberry Pi for that in the past and a cheap Linux VPS right now.

**Comment by Lagari-1** [comment]
Thanks for your help. However I don't have any infrastructure like that. If you provide an infrastructure for yourself,  I would appreciate if you share your bot. This setup seems hard to maintain for personal usage.

**Comment by muerek** [comment]
I agree this is not optimal and I would have liked to see a simpler option, but that's the tools we are given. The code in this repository plus the instructions are how I solved it. 

Unfortunately, I cannot provide a live version of my bot. First, as mentioned in the readme, the current implementation has a major limitation as each instance of the bot can only run one timer. That does not scale for multi-user usage (each user would need their own instance). Second, I do not have the time or budget to provide production-level hosting. All I have is my own crash-and-burn environment that I may use to spin up an instance of the bot from time to time.

**Comment by Lagari-1** [comment]
Thank you for your support.
